kind = "mobile"
previewPath = "/"
title = "IslamNashra"
version = "1.0.0"
id = "artifacts/islamnashra"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/" ]
localPort = 20173

[services.development]
run = "pnpm --filter @workspace/islamnashra run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/islamnashra", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/islamnashra", "run", "serve" ]

[services.env]
PORT = "20173"
BASE_PATH = "/"
