/**
 * News Generation Job
 *
 * Orchestrates the multi-agent news generation pipeline:
 * 1. Runs all 8 AI agents in parallel
 * 2. Content moderation
 * 3. Image fetching for high-significance articles
 * 4. Database insertion
 * 5. Push notifications for breaking/high-significance posts
 */

import { db } from "@workspace/db";
import { postsTable, flaggedPostsTable, userPreferencesTable } from "@workspace/db";
import { generateNewsArticles } from "../lib/newsGenerator";
import { moderateContent } from "../lib/contentModeration";
import { fetchImage } from "../lib/imageProvider";
import { sendPushNotifications } from "../lib/pushNotifications";
import { logger } from "../lib/logger";
import { eq } from "drizzle-orm";

// Daily image budget — Pexels free tier: 20,000/month → 600/day safe
const DAILY_IMAGE_BUDGET = 500;
// Fetch images for articles at or above this significance score
const IMAGE_SCORE_THRESHOLD = 6;
// 72-hour TTL for all posts
const POST_TTL_MS = 72 * 60 * 60 * 1000;

let dailyImageCount = 0;
let imageCountDate = new Date().toDateString();

function resetDailyCountIfNeeded(): void {
  const today = new Date().toDateString();
  if (today !== imageCountDate) {
    dailyImageCount = 0;
    imageCountDate = today;
    logger.info("Daily image count reset for new UTC day");
  }
}

export async function runNewsGenerationJob(): Promise<void> {
  logger.info("News generation job: starting (multi-agent)");

  try {
    const articles = await generateNewsArticles();
    if (articles.length === 0) {
      logger.warn("News generation job: no articles returned from any agent");
      return;
    }

    logger.info({ count: articles.length }, "News generation job: articles generated by all agents");
    resetDailyCountIfNeeded();

    // Sort by significance descending — highest-scored articles get images first
    const sorted = [...articles].sort((a, b) => b.significanceScore - a.significanceScore);

    let published = 0;
    let flagged = 0;

    for (const article of sorted) {
      // Run content moderation using English title + body
      const mod = moderateContent(article.title_en, article.body_en);

      if (mod.flagged) {
        await db.insert(flaggedPostsTable).values({
          title: article.title_en,
          body: article.body_en,
          category: article.category,
          significanceScore: article.significanceScore,
          sourceNote: article.sourceNote,
          flagReason: mod.reason ?? "Flagged by automated content filter",
        });
        logger.warn(
          { title: article.title_en, reason: mod.reason },
          "Article queued for moderation review",
        );
        flagged++;
        continue;
      }

      const now = new Date();
      const expiresAt = new Date(now.getTime() + POST_TTL_MS);

      // Image fetching
      let imageUrl: string | null = null;
      let hasImage = false;

      const eligible =
        dailyImageCount < DAILY_IMAGE_BUDGET &&
        article.significanceScore >= IMAGE_SCORE_THRESHOLD;

      if (eligible) {
        const img = await fetchImage({
          titleEn: article.title_en,
          category: article.category,
        });
        if (img) {
          imageUrl = img.url;
          hasImage = true;
          dailyImageCount++;
        } else {
          logger.warn(
            { title: article.title_en, score: article.significanceScore },
            "Image fetch returned null for eligible article",
          );
        }
      }

      const [post] = await db
        .insert(postsTable)
        .values({
          title: article.title_en,
          body: article.body_en,
          category: article.category,
          imageUrl,
          hasImage,
          significanceScore: article.significanceScore,
          sourceNote: article.sourceNote,
          publishedAt: now,
          expiresAt,
          isBreaking: article.isBreaking,
          titleEn: article.title_en,
          bodyEn: article.body_en,
          titleUr: article.title_ur,
          bodyUr: article.body_ur,
          titleAr: article.title_ar,
          bodyAr: article.body_ar,
        })
        .returning();

      published++;
      logger.info(
        { postId: post.id, category: post.category, score: post.significanceScore, hasImage },
        "Post published",
      );

      // Push notifications for breaking or high-significance articles
      if (post.isBreaking || post.significanceScore >= 8) {
        await notifySubscribers(
          post.id,
          post.title,
          post.body ?? "",
          post.category,
          post.isBreaking ?? false,
        );
      }
    }

    logger.info({ published, flagged }, "News generation job: completed");
  } catch (err) {
    logger.error({ err }, "News generation job: failed");
  }
}

async function notifySubscribers(
  postId: string,
  title: string,
  body: string,
  category: string,
  isBreaking: boolean,
): Promise<void> {
  try {
    const prefs = await db
      .select()
      .from(userPreferencesTable)
      .where(eq(userPreferencesTable.notificationsEnabled, true));

    const tokens = prefs
      .filter((p) => {
        if (!p.pushToken) return false;
        // Breaking news → notify EVERYONE with notifications enabled
        if (isBreaking) return true;
        // High significance → notify subscribers of this category or "all"
        if (p.followedCategories.length === 0) return true;
        return p.followedCategories.includes(category);
      })
      .map((p) => p.pushToken as string);

    if (tokens.length === 0) return;

    const notifTitle = isBreaking ? `🔴 بریکنگ: ${title}` : `📰 ${title}`;
    const notifBody = body.substring(0, 120) + (body.length > 120 ? "…" : "");

    await sendPushNotifications(tokens, notifTitle, notifBody, { postId });
    logger.info({ tokenCount: tokens.length, category, isBreaking }, "Push notifications sent");
  } catch (err) {
    logger.error({ err }, "Failed to send push notifications for post");
  }
}
